import { HTTP_STATUS, type HttpStatus } from './http.js';

export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS: Record<ErrorCode, HttpStatus> = {
  VALIDATION_FAILED: HTTP_STATUS.BAD_REQUEST,
  INVALID_JSON: HTTP_STATUS.BAD_REQUEST,
  PAYLOAD_TOO_LARGE: HTTP_STATUS.PAYLOAD_TOO_LARGE,
  ROUTE_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
  USER_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
  EMAIL_TAKEN: HTTP_STATUS.CONFLICT,
  INTERNAL_ERROR: HTTP_STATUS.INTERNAL_SERVER_ERROR,
};
