import { HTTP_STATUS, type HttpStatus } from './http.js';

export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS: Record<ErrorCode, HttpStatus> = {
  VALIDATION_FAILED: HTTP_STATUS.BAD_REQUEST,
  INVALID_JSON: HTTP_STATUS.BAD_REQUEST,
  PAYLOAD_TOO_LARGE: HTTP_STATUS.PAYLOAD_TOO_LARGE,
  ROUTE_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
  USER_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
  EMAIL_TAKEN: HTTP_STATUS.CONFLICT,
  INVALID_CREDENTIALS: HTTP_STATUS.UNAUTHORIZED,
  UNAUTHORIZED: HTTP_STATUS.UNAUTHORIZED,
  REFRESH_TOKEN_INVALID: HTTP_STATUS.UNAUTHORIZED,
  FORBIDDEN: HTTP_STATUS.FORBIDDEN,
  TOO_MANY_REQUESTS: HTTP_STATUS.TOO_MANY_REQUESTS,
  DATABASE_UNAVAILABLE: HTTP_STATUS.SERVICE_UNAVAILABLE,
  INTERNAL_ERROR: HTTP_STATUS.INTERNAL_SERVER_ERROR,
};
